export const SEARCH_HEROES_REQUEST = "SEARCH_HEROES_REQUEST";
export const SEARCH_HEROES_SUCCESS = "SEARCH_HEROES_SUCCESS";
export const SEARCH_HEROES_FAILURE = "SEARCH_HEROES_FAILURE";
export const LOAD_MORE_HEROES_REQUEST = "LOAD_MORE_HEROES_REQUEST";
export const LOAD_MORE_HEROES_SUCCESS = "LOAD_MORE_HEROES_SUCCESS";
