export const FETCH_HERO_DETAILS_REQUEST = 'FETCH_HERO_DETAILS_REQUEST'
export const FETCH_HERO_DETAILS_SUCCESS = 'FETCH_HERO_DETAILS_SUCCESS'
export const FETCH_HERO_DETAILS_FAILURE = 'FETCH_HERO_DETAILS_FAILURE'